<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: nacer
 * Date: Tue, 17 Nov 2015 08:00:29 +0000
 */

$conf['updatecheck'] = 0;
$conf['proxy']['host'] = 'proxy.ensg.eu';
$conf['proxy']['port'] = 3128;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['datadir'] = '/var/www/dokuwiki/data/pages';
$conf['mediadir'] = '/var/www/dokuwiki/data/pages';
$conf['useacl'] = 1;
// end auto-generated content
